Repository CryptoverseWeb3/Community.CryptoverseWeb3, pull requests merged in 2022-10, with the labels that each got.

#14 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#20 [FEATURE] Join Button now link to discord community account
  src/components/Info/Data.jsx
  src/components/Info/Info.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#23 add: routes to the website
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Pages/Homepage.jsx
  src/components/Dropdowns/Dropdown.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Resources/RoadmapResources/RoadmapResources.jsx
  src/components/Resources/RoadmapResources/RoadmapResourcesElements.jsx
  src/components/index.js
  src/main.jsx
Labels: hacktoberfest-accepted, hacktoberfest, 🥗 status: ready for merge, ✔ status: review complete

#26 add: logo and routes
  package.json
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/NavbarElements.jsx
Labels: hacktoberfest-accepted, hacktoberfest, 🥗 status: ready for merge, ✔ status: review complete

#28 Add icon files
  src/assets/Community Cryptoverseweb3 logo.png
Labels: hacktoberfest-accepted, hacktoberfest, 🥗 status: ready for merge, ✔ status: review complete

#35 Implement Jobs/Internship page and changes Info.jsx to allow display …
  src/Jobs/Data.jsx
  src/Jobs/JobCards.jsx
  src/Jobs/Jobs.jsx
  src/Pages/Homepage.jsx
  src/components/Info/Data.jsx
  src/components/Info/Info.jsx
  src/components/Navbar/Navbar.jsx
Labels: hacktoberfest-accepted, hacktoberfest, 🥗 status: ready for merge, ✔ status: review complete

#36 [FEATURE] Add README.md
  README.md
  src/assets/banner.png
Labels: hacktoberfest-accepted, hacktoberfest, 🥗 status: ready for merge, ✔ status: review complete

#37 a page to show the open source projects
  src/App.css
  src/App.jsx
  src/Pages/Homepage.jsx
  src/components/Info/Data.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/NavbarElements.jsx
  src/components/Projects/AllProjects.jsx
  src/components/Projects/ProjectElement.jsx
  src/components/Projects/Projects.css
  src/components/Projects/Projects.jsx
  src/components/Projects/ProjectsData.jsx
  src/components/Projects/ViewProject.jsx
  src/components/Projects/util.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/SidebarElements.jsx
  src/components/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#39 Add Events page and uuid for React list elements
  package-lock.json
  package.json
  src/Events/Data.jsx
  src/Events/EventElements.jsx
  src/Events/Events.css
  src/Events/Events.jsx
  src/Jobs/JobCards.jsx
  src/Jobs/Jobs.jsx
  src/Pages/Homepage.jsx
  src/assets/images/bitcoin.png
  src/assets/images/blackbox.png
  src/assets/images/blockchain.png
  src/assets/images/nft.png
  src/components/Buttons/ButtonElements.jsx
  src/components/Info/Data.jsx
Labels: hacktoberfest-accepted, hacktoberfest, 🥗 status: ready for merge, ✔ status: review complete

#42 add:Blog Section
  package-lock.json
  src/Blogs/BlogElements.jsx
  src/Blogs/Blogs.css
  src/Blogs/Blogs.jsx
  src/Blogs/Data.jsx
  src/Blogs/assets/img.webp
  src/Pages/Homepage.jsx
  src/components/Info/Data.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/NavbarElements.jsx
Labels: hacktoberfest-accepted, hacktoberfest, 🥗 status: ready for merge, ✔ status: review complete
